version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.13
        working_directory: /go/src/github.com/reedobrien/logging

        environment:
            TEST_RESULTS: /tmp/test-results

        steps:
            - checkout

            - run: mkdir -p $TEST_RESULTS

            - run:
                name: Get packages
                command: |
                  go get github.com/jstemmer/go-junit-report
                  make circle-ready

            - run:
                name: Lint and static analysis
                command:
                    make lint

            - run:
                name: Run unit tests
                command: |
                    trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
                    make test-race |tee ${TEST_RESULTS}/go-test.out
                    make coverage
                    bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
            - store_artifacts:
                path: /tmp/test-results
                destination: raw-test-output

            - store_test_results:
                path: /tmp/test-results

